repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.5.0'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
        name: validate poetry lock
        args: 
        - --check
